courses/urls.py
from django.urls import path
from . import views
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import ExecuteView, ThreadViewSet

router = DefaultRouter()
router.register(r'threads', ThreadViewSet, basename='thread')


urlpatterns = [
    path('add-content/', views.create_content, name='create-content'),
    path('show-content/', views.display_content, name='display_content'),
    path('process-content/<int:content_id>/', views.content_process_form, name='process_content'),
    path('lessons/<int:lesson_id>/', views.lesson_process_code, name='process_lesson'),
    path('process_code/', views.code_process_ai, name='process_code'),
    path('thread_start/', views.start_thread, name='start_thread'),
    path('chat_initialise/', views.chat, name='chat_code'),
    path('thread_retrieve/', views.retrieve_thread, name='retrieve_thread'),
    path('thread_save/', views.save_thread, name='save_thread'),
    path('agent-chat-start/', views.start_group_chat, name='start_chat_with_agent'),
    path('api/code_execute/', ExecuteView.as_view()),
    path('signup/', views.signup, name='signup'),
    path('login/', views.user_login, name='login'),
    path('update_deployment_info/', views.update_deployment_info, name='update_deployment_info'),
    path('get_last_deployment/', views.get_last_deployment, name='get_last_deployment'),
    path('api/', include(router.urls)),
]

mylms/urls.py
# File: project/urls.py

from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
import os
from django.http import HttpResponse, FileResponse
import logging
import mimetypes
logger = logging.getLogger(__name__)

def serve_react_app(request, app_name, path=''):
    if path.startswith('static/'):
        return serve_static(request, app_name, path)

    index_path = os.path.join(settings.DEPLOYED_COMPONENTS_ROOT, app_name, 'index.html')
    if os.path.exists(index_path):
        with open(index_path, 'r') as file:
            content = file.read()
        return HttpResponse(content, content_type='text/html')
    return HttpResponse("App not found", status=404)

def serve_static(request, app_name, path):
    full_path = os.path.join(settings.DEPLOYED_COMPONENTS_ROOT, app_name, 'static', path)
    if os.path.exists(full_path):
        content_type, encoding = mimetypes.guess_type(full_path)
        response = FileResponse(open(full_path, 'rb'), content_type=content_type)
        response['X-Content-Type-Options'] = 'nosniff'
        return response
    return HttpResponse("Static file not found", status=404)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('courses/', include('courses.urls')),
    path('sandbox/', include('sandbox.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    re_path(r'^(?P<app_name>[^/]+)(?P<path>/.*)?$', serve_react_app, name='serve_react_app'),
    # re_path(r'^deployed_apps/(?P<app_name>[^/]+)/static/(?P<path>.*)$', serve_static, name='serve_static'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

courses/models.py
import uuid

from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver


class Code(models.Model):
    code = models.TextField()


class AI_Code(models.Model):
    Input_message = models.TextField()


class Course(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    structure = models.JSONField()  # This field will now store a list of module titles
    objective = models.TextField()
    num_lessons = models.IntegerField(default=0)  # New field for number of lessons
    num_tasks = models.IntegerField(default=0)  # New field for number of lessons

    def __str__(self):
        return self.title

class Module(models.Model):
    number = models.IntegerField()
    title = models.CharField(max_length=100)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

    def __str__(self):
        return f"Module {self.number}: {self.title}"


class Lesson(models.Model):
    number = models.IntegerField()
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=2000)
    module = models.ForeignKey(Module, on_delete=models.CASCADE)

    def __str__(self):
        return f"Lesson {self.number}: {self.title}"


class Task(models.Model):
    task_name = models.CharField(max_length=100)
    description = models.TextField()
    correct_code = models.TextField()
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE)

    def __str__(self):
        return self.task_name


class Task_thread(models.Model):
    thread_id = models.CharField(max_length=200)
    assistant_id = models.CharField(max_length=200)
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    tasks_solved = models.IntegerField(default=0)
    runs = models.IntegerField(default=0)
    prompts = models.JSONField(default=dict)  # Thisfield will now store a list
    learning_thread = models.JSONField(default=list)  # This field will now store a list
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)


class TextContent(models.Model):
    content = models.TextField()


class CodeContent(models.Model):
    code = models.TextField()

from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

class FileStructure(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    path = models.CharField(max_length=1000)
    content = models.TextField(blank=True)
    type = models.CharField(max_length=10)  # 'file' or 'folder'
    parent = models.ForeignKey('self', null=True, blank=True, on_delete=models.CASCADE)

    def get_full_path(self):
        if self.parent:
            return f"{self.parent.get_full_path()}/{self.name}"
        return self.name

class Thread(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='threads')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-updated_at']

    def __str__(self):
        return f"{self.name} - {self.user.username}"

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    last_opened_file = models.ForeignKey('FileStructure', null=True, blank=True, on_delete=models.SET_NULL)
    deployed_apps = models.JSONField(default=dict)

    def __str__(self):
        return self.user.username

    @receiver(post_save, sender=User)
    def create_or_update_user_profile(sender, instance, created, **kwargs):
        if created:
            UserProfile.objects.create(user=instance)
        else:
            instance.userprofile.save()

courses/forms.py
from django import forms
from .models import Course, Code, AI_Code


class ContentForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ['title', 'objective', 'description']


class CodeForm(forms.ModelForm):
    class Meta:
        model = Code
        fields = ['code']



class GeneratedContentForm(forms.Form):
    prompts = forms.CharField(widget=forms.Textarea, help_text="Enter each prompt on a new line.")

    # Add other fields for parameters as needed

courses/views.py
import logging
from rest_framework import viewsets, status
from rest_framework.decorators import action
from rest_framework.permissions import IsAuthenticated
from .models import Thread, UserProfile
from .serializers import ThreadSerializer
import uuid
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login
from asgiref.sync import sync_to_async, async_to_sync
import json
import os
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
import asyncio
from django.contrib.auth import get_user_model
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse, HttpResponse
from openai import OpenAI
from .forms import ContentForm, CodeForm
from django.shortcuts import get_object_or_404, redirect
from .models import Course, Module, Lesson, Task, Task_thread
from .openai_service import generate_lesson_content, generate_project_content, assistant_thread_run, \
    assistant_preprocess_task, coding_bot_calling, run_loop
from django.shortcuts import render
from .openai_service_frontend import interface_bot_calling
from .python_execution import run_streamlit_app, read_streamlit_code, read_code,  execute_python_code
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.views.decorators.http import require_http_methods

client = OpenAI(api_key=os.environ.get('OPENAI_API_KEY'))


# Enable logging
logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger(__name__)
User = get_user_model()
from django.contrib.auth.models import User
from courses.models import UserProfile

@csrf_exempt
@require_http_methods(["POST"])
def user_login(request):
    for user in User.objects.all():
        UserProfile.objects.get_or_create(user=user)
    data = json.loads(request.body)
    username = data.get('username')
    password = data.get('password')

    if username is None or password is None:
        return JsonResponse({'message': 'Please provide both username and password'}, status=400)

    user = authenticate(username=username, password=password)

    if user is not None:
        login(request, user)
        return JsonResponse({
            'message': 'Login successful',
            'user': {
                'id': user.id,
                'username': user.username,
                'email': user.email
            }
        }, status=200)
    else:
        return JsonResponse({'message': 'Invalid credentials'}, status=401)


@csrf_exempt
@require_http_methods(["POST"])
def signup(request):
    data = json.loads(request.body)
    username = data.get('username')
    email = data.get('email')
    password = data.get('password')

    if not all([username, email, password]):
        return JsonResponse({'message': 'Please provide all required fields'}, status=400)

    try:
        user = User.objects.create_user(username=username, email=email, password=password)
        return JsonResponse({'message': 'User created successfully', 'id': user.id}, status=201)
    except Exception as e:
        return JsonResponse({'message': str(e)}, status=400)

@csrf_exempt
@login_required
@require_http_methods(["POST"])
def update_deployment_info(request):
    data = json.loads(request.body)
    file_name = data.get('file_name')
    deployment_info = data.get('deployment_info')

    if not all([file_name, deployment_info]):
        return JsonResponse({'message': 'Please provide both file_name and deployment_info'}, status=400)

    try:
        user_profile, created = UserProfile.objects.get_or_create(user=request.user)
        user_profile.deployed_apps[file_name] = deployment_info
        user_profile.save()
        return JsonResponse({'status': 'success', 'message': 'Deployment info updated'})
    except Exception as e:
        return JsonResponse({'status': 'error', 'message': str(e)}, status=500)


@require_http_methods(["GET"])
def get_last_deployment(request):
    user_id = request.GET.get('user_id')
    file_name = request.GET.get('file_name')

    if not user_id or not file_name:
        return JsonResponse({'status': 'error', 'message': 'Missing user_id or file_name'}, status=400)

    try:
        user_profile = UserProfile.objects.get(user_id=user_id)
        deployment_info = user_profile.deployed_apps.get(file_name)

        if deployment_info:
            return JsonResponse({
                'status': 'success',
                'deployment': deployment_info
            })
        else:
            return JsonResponse({
                'status': 'success',
                'deployment': None
            })
    except UserProfile.DoesNotExist:
        return JsonResponse({
            'status': 'success',
            'deployment': None
        })
    except Exception as e:
        return JsonResponse({'status': 'error', 'message': str(e)}, status=500)



class ThreadViewSet(viewsets.ModelViewSet):
    serializer_class = ThreadSerializer
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        return Thread.objects.filter(user=self.request.user)

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)

    @action(detail=False, methods=['get'])
    def get_or_create_default(self, request):
        default_thread, created = Thread.objects.get_or_create(
            user=request.user,
            name="Default Thread",
        )
        serializer = self.get_serializer(default_thread)
        return Response(serializer.data)

    def get_queryset(self):
        return Thread.objects.filter(user=self.request.user)

    def create(self, request, *args, **kwargs):
        name = request.data.get('name', 'Default Thread')
        thread, created = Thread.objects.get_or_create(
            user=request.user,
            name=name
        )
        serializer = self.get_serializer(thread)
        return Response(serializer.data, status=status.HTTP_201_CREATED if created else status.HTTP_200_OK)


class ExecuteView(APIView):
    @method_decorator(csrf_exempt)
    def dispatch(self, *args, **kwargs):
        return super(ExecuteView, self).dispatch(*args, **kwargs)

    def post(self, request, *args, **kwargs):
        print("post request received")
        message = request.data.get('message')
        code = message.get('code')  # Assuming the code is submitted in the request
        input_values = message.get('input_values')  # Assuming input values are provided
        try:
            response = execute_python_code(code, input_values)
            if len(response) > 4:
                output, complete, prompt_line_n, message, image = response
                print("response", response)
                return Response(
                    {'output': output,
                     'completion': complete,
                     'prompt_line_n': prompt_line_n,
                     'message': message,
                     'image': image,
                     }, status=status.HTTP_200_OK)
            else:
                output, complete, prompt_line_n, message = response
                print("response", response)
                return Response(
                    {'output': output,
                     'completion': complete,
                     'prompt_line_n': prompt_line_n,
                     'message': message,
                     }, status=status.HTTP_200_OK)
        except Exception as e:
            logger.error(f"Error during code execution: {str(e)}", exc_info=True)
            return Response({'error': 'An error occurred during code execution'},
                            status=status.HTTP_500_INTERNAL_SERVER_ERROR)


async def start_group_chat(request):
    print("check if coding_chat started")
    if request.method == 'POST':
        # Extract message from request asynchronously
        message = await sync_to_async(request.POST.get)('input_message')

        # Assuming `app_1.callback` can be awaited, otherwise you need to adapt it

        print("response", response)

        # Reading code can be done asynchronously if I/O bound
        streamlit_code = await sync_to_async(read_streamlit_code)()
        code = await sync_to_async(read_code)()

        # Run the async code execution, adjust `run_streamlit_app` to be async
        process = await run_streamlit_app(streamlit_code)

        # Using subprocess properly in AsyncIO, depending on your implementation
        completion = process.poll()
        output, error = await process.communicate()

        return JsonResponse({
            'completion': completion,
            'response': response,
            'code': code,
            'streamlit_code': streamlit_code,
            'output': output.decode() if output else "",
            'error': error.decode() if error else ""
        })


def start_code_verify(request):
    print("check if coding started")
    if request.method == 'POST':
        message = request.POST.get('input_message')
        code = ""
        language = "Python"
        # message = "Define a function censor_python that takes one parameter:   \
        #        Name: input_strs, Type: list of str, Example Input: [“python“, “hello“, “HELLO“]\
        #     When called, the function should return a new list of strings with the letters “P”,\
        #      “Y”, “T”, “H”, “O”, “N” replaced with “X”, the solution should be case insensitive."
        result = ""
        criteria = ""
        action = ""
        interface_code = ""
        streamlit_code = """
import streamlit as st
import subprocess
import threading
import queue
import time
output_queue = queue.Queue()
class ProcessHandler(threading.Thread):
    def __init__(self, filepath):
        super().__init__()
        self.filepath = filepath
    def run(self):
        with subprocess.Popen(["python3", self.filepath], stdout=subprocess.PIPE) as p:
            for line in p.stdout:

courses/templates/courses/Code_form.html
<form method="post">
    {% csrf_token %}
    <textarea name="code_input" id="code_input" cols="30" rows="10" placeholder="Enter Python code here"></textarea>
    <button type="submit">Execute</button>
</form>
<textarea id="code_output" cols="30" rows="10" placeholder="Output will appear here" readonly></textarea>

courses/templates/courses/Course_module_list.html
{% extends 'courses/base.html' %}

{% block title %}Reprocess Content{% endblock %}

{% block content %}
    <h1>Process Content</h1>
<div>


        <h2>Course title:</h2>
        <pre><code class="language-python">{{ course.title|safe }}</code></pre>
        <h2>Course Objective:</h2>
        <pre><code class="language-python">{{ course.objective|safe }}</code></pre>
         <h2>Course Description:</h2>
        <pre><code class="language-python">{{ course.description|safe }}</code></pre>
    <h2>Lessons:</h2>
     {% for module in modules %}
     <div>Module #{{ module.number }}</div>
     <div>{{ module.title }}</div>
        {% for lesson in module.lesson_set.all %}
        <div>Lesson #{{ lesson.number }}</div>
        <div></div>
        <button><a href="{% url 'process_lesson' lesson.id %}">{{ lesson.title }}</a></button>
        {% endfor %}
    {% endfor %}
    <hr>
</div>
{% endblock %}

courses/templates/courses/Show_content_generation_form.html
{% extends 'courses/base.html' %}

{% block title %}Add Content{% endblock %}

{% block content %}
    <h1>Generate Content</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Generate</button>
    </form>
{% endblock %}

courses/templates/courses/Show_courses_list.html
{% extends 'courses/base.html' %}

{% block title %}Display Content{% endblock %}

{% block content %}
    <h1>Saved Content</h1>
   {% for course in courses %}
    <div>
        <h2>Course Title:</h2>
        <p>{{ course.title }}</p>
        <h2>Objective:</h2>
        <p>{{ course.objective }}</p>
         <li>Course Structure</li>
        {% for module in course.structure %}
        <div>Module: {{ module.title }}</div>
        {% endfor %}
        <!-- Add a link or form for processing content -->
        <form action="{% url 'process_content' course.id %}" method="post">
            {% csrf_token %}
            <input type="submit" value="Re-process Content">
        </form>
        <hr>
    </div>
{% empty %}
    <p>No content has been saved yet.</p>
{% endfor %}
{% endblock %}

courses/templates/courses/Show_lesson_process_page.html
{% extends 'courses/base.html' %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
{% block title %}Reprocess Content{% endblock %}

{% block content %}
<h1>{{ lesson.title }}</h1>

{% for task in lesson.task_set.all %}
<div>
    <h3>{{ task.name }}</h3>
    <h4>{{ task.description }}</h4>

        <textarea id="task-{{ task.id }}" placeholder="Output will appear here">{{ task.correct_code }}</textarea>
         <button class="input-button" onclick="">Send for execution</button>
         <button is="retrieve-task-{{ task.id }}" class="input-button" onclick="handleRetrievalClick('{{ task.id }}')">Retrieve thread history</button>
    <script>
    const taskBlock{{ task.id }} = CodeMirror.fromTextArea(document.getElementById('task-' + {{ task.id }}), {
        lineNumbers: false,
        mode: 'python',
        theme: 'ayu-mirage',
        readOnly: true
    });

    const taskElement{{ task.id }} = taskBlock{{ task.id }}.getWrapperElement();
    taskElement{{ task.id }}.classList.add('customClass');
</script>
</div>
{% endfor %}
<div id="my-element" data-start-thread-url="{% url 'start_thread' %}">
    <!-- Your HTML content here -->
</div>
<div class="container">
    <div class="form-container">
        <div id="wrapper-left" class="form-wrapper-left" data-start-interpreter="{% url 'process_lesson' lesson.id %}">
            <h2>Practice section:</h2>
            <form id="code-form">
                {% csrf_token %}
                <textarea name="code" id="code" placeholder="Your code here"></textarea>
                <p><button class="button-soft" type="submit">Run Code</button></p>
            </form>



            <div class="output-container">
                <textarea id="code_output" placeholder="Output will appear here"></textarea>

            </div>
        </div>
        <div class="form-wrapper-right">
            <div id="preview"></div>
            <form id="code-form-ai" novalidate>
                <h2>AI CoPilot:</h2>
                {% csrf_token %}
                <textarea id="ai-output" name="ai-output" style="height: 80%;" placeholder="AI output will appear here"></textarea>

            </form>
            <form id="code-input-ai" novalidate>
                <p><button class=button-soft type="submit">Send Message</button></p>
                {% csrf_token %}
                <textarea id="ai-input" name="ai-output" style="height: 20%;" placeholder="AI output will appear here"></textarea>

            </form>
        </div>
    </div>
</div>

<h2>ML Chart</h2>

<div id="plotImage"></div>



<!-- Import React and any necessary libraries -->
<script src="https://unpkg.com/react@17/umd/react.development.js"></script>
<script src="https://unpkg.com/react-dom@17/umd/react-dom.development.js"></script>

<!-- Mount React component to root element -->
<script src="{% static 'js/scripts.js' %}"></script>
    <hr>
{% endblock %}

courses/templates/courses/Show_lesson_process_page_reserve.html
{% extends 'courses/base.html' %}

{% block title %}Reprocess Content{% endblock %}

{% block content %}
    <h1>Process Content</h1>
<div>
    <h2>Lesson title:</h2>
    <pre><code class="language-python">{{ lesson.title|safe }}</code></pre>
    <h2>Lesson Description:</h2>
    <pre><code class="language-python">{{ lesson.description|safe }}</code></pre>
    <h2>Tasks:</h2>
     {% for task in tasks %}
    <pre><code class="language-python">{{ task.id }}</code></pre>
    <pre><code class="language-python">{{ task.title }}</code></pre>
    <pre><code class="language-python">{{ task.content }}</code></pre>
    <form id="code-form" novalidate>
    {% csrf_token %}
    {{ form.as_p }}
        <p>
    <button type="submit">Run Code</button>
        </p>
    </form>
        <textarea id="code_output" cols="200" rows="10" placeholder="Output will appear here">   </textarea>
    <script>
// Define a global variable to store the prompt message
let promptMessage = '';

document.addEventListener('DOMContentLoaded', function () {
    const form = document.getElementById('code-form');
    var output_form = CodeMirror.fromTextArea(document.getElementById('code_output'), {
        lineNumbers: true,
        mode: "text",
        theme: "default"
    });
    var editor = CodeMirror.fromTextArea(form.querySelector('textarea'), {
        lineNumbers: true,
        mode: "python",
        theme: "default"
    });

    // Define the event listener for form submission
    form.addEventListener('submit', handleFormSubmission);

    // Function to handle form submission
    function handleFormSubmission(event) {
        event.preventDefault();

        const code = editor.getValue();
        const formData = new FormData(form);
        formData.append('code', code);

        fetch('{% url 'process_lesson' lesson.id %}', {
            method: 'POST',
            body: formData,
            headers: {
                'X-CSRFToken': 'ZUP3t44Y65LUc73Xf9Ttev8TnyHF3QzKk4gmydjMKbletcifqGx3RUGNzQoH5WeK'
            }
        })
        .then(response => {
            if (!response.ok) {
                throw new Error('Network response was not ok');
            }
            return response.json();
        })
        .then(data => {
            // Store the prompt message globally
            promptMessage = data.prompt_message;

            if (data.input_requested) {
                // Display prompt message and input field
                const updatedCode = '\n' + promptMessage + ' ';  // Append prompt message with space
                output_form.setValue(updatedCode);

                // Remove the form submission event listener to prevent multiple submissions
                form.removeEventListener('submit', handleFormSubmission);

                // Handle form submission with input value
                form.addEventListener('submit', handleInputSubmission);
            } else {
                // No input requested, update output form with the response
                output_form.setValue(data.output);
            }
        })
        .catch(error => {
            console.error('Error:', error);
            output_form.setValue('An error occurred while processing your request.');
        });
    }

    // Function to handle form submission with input value
    function handleInputSubmission(event) {
        event.preventDefault();

        // Get the user input from the last line of the output form
        const lines = output_form.getValue().split('\n');
        const lastLine = lines[lines.length - 1].trim();
        const userInput = lastLine.substring(promptMessage.length).trim();

        const formData = new FormData(form);
        formData.append('input_value', userInput);

        // Send the form data to the server
        fetch('{% url 'process_lesson' lesson.id %}', {
            method: 'POST',
            body: formData,
            headers: {
                'X-CSRFToken': 'ZUP3t44Y65LUc73Xf9Ttev8TnyHF3QzKk4gmydjMKbletcifqGx3RUGNzQoH5WeK'
            }
        })
        .then(response => {
            if (!response.ok) {
                throw new Error('Network response was not ok');
            }
            return response.json();
        })
        .then(data => {
            // Update output form with the response
            const currentCode = output_form.getValue();  // Get current code in output_form
            const updatedCode = currentCode + '\n' + data.output;  // Append output on a new line
            output_form.setValue(updatedCode);
            // Move cursor to the next line for the next execution step
            output_form.setCursor({ line: output_form.lineCount() });
        })
        .catch(error => {
            console.error('Error:', error);
            output_form.setValue('An error occurred while processing your request.');
        });
    }
});

    </script>
 <!--   <script>
    var editor_1 = CodeMirror.fromTextArea(document.getElementById('code_output {{ task.id }}'), {
    lineNumbers: true,
    mode: "python", // or any other mode you need
    theme: "default"
    });

    </script>-->
    {% endfor %}
    <hr>
</div>
{% endblock %}

courses/templates/courses/process_code.html
{% extends 'courses/base.html' %}

{% block title %}{% endblock %}

{% block content %}
    <h1>Convert into Code</h1>
<div>

<h2>Prompt:</h2>
        <p>{{ content.prompt }}</p>
        <h2>Response:</h2>
        <pre><code class="language-python">{{ content.response|safe }}</code></pre>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Process</button>
    </form>
    <hr>
</div>
{% endblock %}